name = "MyPkg36"
uuid = "cba5d094-88a5-48d0-b067-b158f59c87b2"
authors = ["Shuhei Ohno"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.11"
